version: '3.8'
services:
  go:
    build: ./
    container_name: go
    volumes: 
      - .:/usr/src/app
    tty: true
    ports:
      - 8080:8080
    networks:
     - api

  mongo: 
    container_name: mongo
    image: mongo:latest
    ports:
      - 27017:27017
    networks:
     - api

networks:
  api:
    driver: bridge  